'use client';

import { motion, AnimatePresence } from 'framer-motion';
import { Brain } from 'lucide-react';
import { TopicWithMetadata } from '../../hooks/useTopics';

interface QuizGenerationModalProps {
  isVisible: boolean;
  topic: TopicWithMetadata | null;
}

export const QuizGenerationModal = ({ isVisible, topic }: QuizGenerationModalProps) => {
  if (!isVisible) return null;
  
  return (
    <AnimatePresence>
      <motion.div 
        className="fixed inset-0 bg-black/40 backdrop-blur-lg flex items-center justify-center p-4 z-50"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
      >
        <div className="retro-card-group relative">
          <div className="retro-pattern-overlay" />
          <motion.div 
            className="retro-card bg-white p-6 sm:p-8 w-full max-w-sm mx-4 z-[2]"
            initial={{ scale: 0.8, rotate: -5, opacity: 0 }}
            animate={{ scale: 1, rotate: 0, opacity: 1 }}
            exit={{ scale: 0.8, rotate: 5, opacity: 0 }}
            transition={{ type: "spring", stiffness: 300, damping: 25 }}
          >
            <div className="retro-title-header">
              <span>🤖 AI Magic in Progress</span>
            </div>
            
            <div className="px-[1.5em] py-[1.5em] text-center">
              <div className="w-16 h-16 sm:w-20 sm:h-20 bg-[#7C65C1] rounded-[0.4em] border-[0.2em] border-[#050505] shadow-[0.3em_0.3em_0_#000000] flex items-center justify-center mx-auto mb-4 sm:mb-6">
                <Brain className="w-8 h-8 sm:w-10 sm:h-10 text-white animate-pulse" />
              </div>
              
              <div className="retro-info-box mb-4 bg-[#fffbeb]">
                <p className="text-[#050505] font-bold text-sm sm:text-base mb-2">
                  ✨ Did you know?
                </p>
                <p className="text-[#050505] text-xs sm:text-sm leading-relaxed font-semibold">
                  Each player gets <span className="font-bold text-[#f59e0b]">unique questions</span> generated by AI! 
                  No two quests are ever the same! 🎯
                </p>
              </div>
              
              <p className="text-[#050505] mb-2 text-sm sm:text-base font-semibold">
                🎮 Crafting your personalized quest about
              </p>
              
              <p className="font-black text-[#050505] mb-4 sm:mb-6 text-sm sm:text-base">
                {topic?.title} ⚡
              </p>
              
              <div className="flex justify-center space-x-3 mb-4">
                {[0, 1, 2].map((i) => (
                  <div
                    key={i}
                    className={`w-3 h-3 rounded-[0.2em] border-[0.1em] border-[#050505] animate-bounce ${
                      i === 0 ? 'bg-[#f59e0b]' : i === 1 ? 'bg-[#7C65C1]' : 'bg-[#10b981]'
                    }`}
                    style={{ animationDelay: `${i * 0.2}s` }}
                  />
                ))}
              </div>
              
              <p className="text-xs sm:text-sm text-[#6b7280] animate-pulse font-semibold">
                🚀 AI is brewing your unique challenge...
              </p>
            </div>
          </motion.div>
        </div>
      </motion.div>
    </AnimatePresence>
  );
};

